athlete_id: matti-rowe
generated_date: '2025-12-18 13:05:57'
tier: compete
plan_weeks: 24
race:
  id: unbound_gravel_200
  name: Unbound Gravel 200
  date: '2026-06-07'
strength_frequency: 2
exercise_exclusions:
- Box Jump
- Jump Squat
equipment_tier: moderate
key_days:
- monday
- tuesday
- thursday
- saturday
strength_days:
- sunday
- saturday
