athlete_id: test-email-1766157204
generated_date: '2025-12-19 15:13:49'
tier: compete
plan_weeks: 24
race:
  id: unbound_gravel_200
  name: Unbound 200
  date: '2026-06-07'
strength_frequency: 2
exercise_exclusions: []
equipment_tier: minimal
key_days:
- tuesday
- thursday
- saturday
strength_days:
- sunday
- saturday
